[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/media/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000, s-maxage=2592000, immutable"

[[headers]]
  for = "/me.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000, s-maxage=2592000"

[[headers]]
  for = "/static/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
